[package]
name = "baby_wolfie"
version = "1.0.0"
authors = []

[addresses]
owner="ce910c5fa159318c1a1f9847e56ff2866cfd327514c9e89f073987c9a4e95469"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"




[dev-dependencies]
