[package]
name = "baby_wolfie"
version = "1.0.0"
authors = []

[addresses]
owner="9c3d1a36c42cc0c7dea0d3a8409f135703d9302f2cb05b26dada780a108dc7dd"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"




[dev-dependencies]
